### ISSUE TITLE
Channel SVT Play (swedish) is lagging badly

### ISSUE THREAD

**Issue by KDanielK** [RasPlex/RasPlex#107]
Hi,

The channel is lagging badly on RasPlex, it works great on other Plex clients.

This issue has been consistant since atleast 1st of December according to this thread in the forum https://forums.plex.tv/index.php/topic/88117-problems-with-swedish-channel-svt-play

BR/Daniel

**Comment by NedtheNerd** [comment]
Is this still an issue in 0.5.1?

If not can you please close this issue.

**Comment by g1t-dlanor** [comment]
I've now tested this issue again using various RasPlex versions, including a current pre-release WIP (for what may become RasPlex 0.7.0), and I see no trace of the jerkiness and other problems reported above. I'm not sure how much our ffmpeg improvements helped with this though, as I now also get perfect playback from the SVT channel when using older RasPlex versions such as 0.4.1, which used to have the problem reported above. So I think that the SVT channel must have changed their streaming software/methods to improve generic player compatibility. It doesn't really matter if our changes or theirs are responsible for the improvements. Either way, this issue is no longer a problem, so I'm closing it.
