### ISSUE TITLE
Language settings result in Plex & Rasplex crash

### ISSUE THREAD

**Issue by raxxy** [RasPlex/RasPlex#111]
Tested across 2 pi's, not always the same language, occasionally the crash will completely crash the pi requiring a reboot, or will just lock up plexHT and it will recover its self after a period of 2-5 minutes.

This issue appears to be a problem with all of them, English US to Esperanto (going up) as well as changing dutch, to danish, to the next one (never got there, going down)

**Comment by jarlis** [comment]
I dont think that this issue is solved. ive tested rasplex 0.4.1, 0.5.0 and 0.5.1 on my raspberry (512mb ram) model and still get the issue where it occasionally crashes the pi. it does also not save the language settings however it saves the other changes like location etc. issue better described in #110.

Also during the installation of rasplex it preloads the local language (swedish), when changing to english it does not correct all the buttons/text to english nor does it change the language to english once its installed (menu's showed in mixed eng and swedish). this have been the same during installation of 0.4.1 to 0.5.1.

**Comment by g1t-dlanor** [comment]
I find your installation results in contradiction to my own, and I wonder what causes the difference.

I too am Swedish, situated in a suburban of Stockholm and using one of the major broadband ISPs around here (Bahnhof). But every time I install RasPlex (all versions since a LONG time back) it always uses English as the default language. I think there's an option to change language in the first-time-run 'wizard' of RasPlex, but if you skip that change (like I always do) it should continue using the original default language, which is English. I have never experienced the 'preload' of Swedish language that you describe. This could be due to failure to identify my location through the ISP connection, as my timezone info is usually incorrect until I change it. But when I install and run RasPlex through BerryBoot RasPlex does identify my timezone as Swedish automatically, and even then I still get English language as default, so I doubt that's the reason.

As for crashing during language changes, I haven't tested it much, so I'll have to try some changes back and forth between the languages I can handle (don't want to get lost in unreadable menus... ;) ).

----- Some tests later -----
I have now performed some tests as follows:
1: Booted RasPlex 0.5.0, starting with English language (what I normally use)
2: Used 'Preferences' to switch language to Swedish, which took appx 1 minute to complete
3: Used main menu's sidemenu command "Starta Om" to reboot RasPlex
4: RasPlex now booted into Swedish language as it should.
NB: In Swedish and most non-English languages the translations are partly incomplete, leading to continued use of English for all words and phrases lacking translation. Proper names are also never translated, which includes the names of media sections, so much of the main menu may still look English, if such section names were chosen in creating the sections.
5: Used the 'Inställningar' to switch 'Språk' to 'English (US)' which took appx 1 minute to complete
6: changed my mind and switched language to just 'English' which took several minutes to complete, and resulted in various abnormal displays of the preferences menu before completion. During this interval I almost reset the RPi, thinking it might have crashed. But I held out and just pressed escape and 'H' repeatedly in an attempt to reach the home menu, which eventually succeeded.
7: Home menu was opened in English language
8: I used the "Restart" command to reboot RasPlex again.
9: RasPlex rebooted into English language and behaving normally

Conclusion:
There is some problem with the language change which can cause it to take a very long time, several minutes, instead of the usual time of appx one minute. But even then it is possible for the change to complete, if you just have patience enough to wait a few minutes more, despite the odd screen updates that may occur (I gradually lost existing text from the menu, until it was all black, shortly before successfully exiting to main menu). That odd behaviour needs to be explored and fixed in coding, but even without such changes it was still possible for me to succeed in the language changes, and hopefully it will work for you as well.

While the problem I saw was non-fatal (recovered without a real crash) it is nevertheless a serious flaw that needs to be fixed, so I'm leaving this issue open until it has been properly fixed.

**Comment by g1t-dlanor** [comment]
@jarlis:
Another beta tester has suggested that CEC settings may have caused your RasPlex to adopt language settings from your TV sets, since that is one of the available CEC functions. This would explain the automatic use of Swedish language during installation, and might also cause an override over your manual settings. If so, then you need to edit the CEC settings in the RasPlex submenu Preferences > System > Input devices > Peripherals > CEC Adapter, so as to disable the setting entitled "Use the TV's language setting".

NB: If this fix helps, then it means that your problem is not the same as that of the original poster.
That problem remains real, and needs a coded fix to remove the abnormal results I saw in my test.

**Comment by jarlis** [comment]
after reading your comment i checked the RasPlex submenu Preferences > System > Input devices > Peripherals > CEC Adapter. and found the TV (didn't know rasplex had this connection with the tv) however when checking the settings i found that "Use the TV's language setting" was unticked by default... however i proceeded to test to change the language on the TV and hey presto! it worked. after testing back and forth (disabling the CEC was not a good idea as the remote also got disconnected...) but it seems that my TV (Samsung) have its own little &%" system called Anyconnect (or something like that) that's also involved. but after unticking "Use the TV's language setting", restarting rasplex, and ticking it again, changing language and restarted again it now holds :) PS. the rasplex probably did never crash when i changed language, it just felt like it after a longer while. But thank you so much for your assistance in this! maybe this thing might be worth mentioning somewhere for rasplex beginners like me. as ive said, i tested 0.4.1, 0.5.0 and 0.5.1 with the same result, but i never got this issue in XBMC/Kodi (Raspbmc and Raspbian).

**Comment by NedtheNerd** [comment]
CEC and its settings are enabled by default, and has been in all CEC enabled releases you must have changed this setting at some time, I have just checked this with a fresh install of 0.4.1, 0.5.0 and 0.5.1.
