### ISSUE TITLE
video stops randomly

### ISSUE THREAD

**Issue by IAmBecomeDeth** [RasPlex/RasPlex#122]
Size of Raspberry Pi: 512
Type of SD card: SDHC 10
Internet connection type: Ethernet
Version of RasPlex: 2014-01-17 wip
Log files...which logs do you need?
How did you install rasplex? gui installer windows

Best description you can give of the problem
Steps to reproduce (what were you doing when it happened? Can you make it happen again?)

Sometimes every 5 minutes, sometimes works fine for hours. I can't explain it yet. 

Audio stops first, video slows (just slightly) then stops after aproximately 1-2s. 

It doesn't ALWAYS lock up while playing. ocasionally it will lock up during pause/unpause. Once it stops, plex refuses to respond. play/pause/stop/exit/ff/rw/info...nothing. 

Oddly enough, even though plex doesn't respond, the system isn't FULLY locked up. When it locks while paused, the dim screensaver works perfectly, and will undim when I press buttons on my remote. 

Helpful

Version of Plex Server
Type of plex server: local linux 0.9.8.17
Power supply type and power rating TX-NR717 ...can't find amperage, but it's MHL. Also happens on 2.1A rocketfish adapter that I charge my android phone with.
Comment on system load, cpu usage, and free memory (ssh in and run 'top' and 'free -m')
i will try this the next time, forgot to test ssh last time...

**Comment by snajjar** [comment]
Hello, i have the exact same issue on 0.4.1.

Audio drops, then a couple of seconds later, video drops too and RasPlex is crashed. Happens randomly (about 2-3 times per hour). It seems that somehow, RasPlex dropped the Plex connection to the server, but works again after hard reboot of the Pi.

I have 2 plex servers and it happens while watching stuff on both of them, so it seems to be RasPlex-related (network-related seems unlikely because the rest of the network is working fine when plex crashes).

I have a very simple network configuration, Pi and Server are behind the same router. RasPlex is configured on a static IP. What can i do to help?

It happens

**Comment by snajjar** [comment]
@mysteryman69 Since this is to be RasPlex-Network related, i have to ask: did you configure your RasPlex on a static IP like i did? If so, maybe there's an investigation to start here.

**Comment by g1t-dlanor** [comment]
@snajjar:
If you insist on using the now obsolete RasPlex version 0.4.1, then of course you are going to have problems with it. And those problems can only be fixed by updating the program. The version 0.4.1 is more than half a dozen stable releases older than the current one (v1.0.1), and there have been a HUGE number of internal beta test versions in between, all with various changes and improvements. I strongly suggest that you upgrade your installation to the current version, which is v1.0.1 at present, with v1.0.2 release being expected momentarily.

NB: Due to the wide gap in versions between 0.4.1 and the current releases, you can't use the internal update method built into the program. (It has been modified since then.) So you will need to do a fresh install instead.

**Comment by NedtheNerd** [comment]
@snajjar 

0.4.1 was released in April 2014. Not only has there been a number of updates to Rasplex since then there have also been a number of releases of PMS which potentially cause issues with old Plex clients, as dlanor says please update Rasplex to the latest version and I would also suggest that you update your PMS at the same time.

This issue will not be re-opened.

**Comment by snajjar** [comment]
Ok, i got it.

I still want to mention i didn't insit on using 0.4.1.
I tried to run the software update several time, but it always got me the "Up to date" answer, so i thought it was the last version.

I'll update RasPlex manually, thank you.

**Comment by g1t-dlanor** [comment]
I see. The reason for your update attempts failing is probably twofold. Some of the releases were made in a different 'channel' than the one called "stable" inside the program (even though I consider them stable releases), so you would only see those if you switched channel to preview/pre-release. Another reason is that we needed to modify the update server and the client methods to access it, which unfortunately means that older clients no longer work with it. Hopefully everything will work better for you with the newer RasPlex versions.

**Comment by mquestier1** [comment]
Hi,
I have the same problem with a new Pi 2 running 1.0.2.
I've added my Plexserver with the ip in Rasplex.
The network connection works according to me because previously i've used an Pi B without any
problems for over a year.

I've also looked in the logfile.  Is it normal that the file is +400Mb?
This is the end of that file.  

`19:36:35 T:1595929664   ERROR: Texture manager unable to load file: special://masterprofile/Thumbnails/
19:36:35 T:1595929664   ERROR: Previous line repeats 2 times.
19:36:35 T:1595929664   ERROR: Delete - Error deleting file plexserver://0b67cd3392f787b590fbc41e9ae8a140fb873ee0/photo/:/transcode?height=2048&url=http%3a%2f%2f127.0.0.1%3a32400%2flibrary%2fmetadata%2f3325%2fart%2f1424077060&width=2048
19:36:35 T:1614804032   ERROR: Delete - Error deleting file plexserver://0b67cd3392f787b590fbc41e9ae8a140fb873ee0/photo/:/transcode?height=2048&url=http%3a%2f%2f127.0.0.1%3a32400%2flibrary%2fmetadata%2f6821%2fart%2f1406207709&width=2048
19:36:35 T:1595929664   ERROR: Delete - Error deleting file plexserver://0b67cd3392f787b590fbc41e9ae8a140fb873ee0/photo/:/transcode.dds?height=2048&url=http%3a%2f%2f127.0.0.1%3a32400%2flibrary%2fmetadata%2f3325%2fart%2f1424077060&width=2048
19:36:35 T:1595929664   ERROR: Texture manager unable to load file: special://masterprofile/Thumbnails/
19:36:35 T:1614804032   ERROR: Previous line repeats 1 times.
19:36:35 T:1614804032   ERROR: Delete - Error deleting file plexserver://0b67cd3392f787b590fbc41e9ae8a140fb873ee0/photo/:/transcode.dds?height=2048&url=http%3a%2f%2f127.0.0.1%3a32400%2flibrary%2fmetadata%2f6821%2fart%2f1406207709&width=2048`

What can i do to sort the problem.
I could go back to my old Pi but you know the Pi2 is a new toy...
