### ISSUE TITLE
Volume gets louder when changin audio tracks on videos

### ISSUE THREAD

**Issue by cpfaff** [RasPlex/RasPlex#282]
When changing audio tracks on playing videos the audio level is jumping up and it gets louder. I am on the latest rc.

**Comment by muppet3000** [comment]
I have exactly the same problem, I have 2 Pis, one running 0.5.0 and one running 0.4.1.
It's definitely a problem on 0.5.0 and I will test the 0.4.1 one tonight(although I'm certain it also affects this one).
Best way to replicate is (using Android Plex remote):
1) Play a music album (on the selected Pi);
2) Switch the app into 'remote' mode;
3) Use the 'volume' slider to set the volume to quiet/almost off;
4) Wait for the song to end, when the next song starts it will jump back to the original volume.

Hopefully others can confirm that the same steps cause the same problem for them. Does anyone have a work around?

Looking forward to seeing this one fixed, I have a TV-less Pi setup in my kitchen just for music and the speaker's always set to full volume so that I can control it on the Pi, only I have to change the volume for every song! (Before anyone suggests changing the volume on the speaker it's on top of a kitchen unit so I'd have to go climbing everytime I wanted to change the volume).

Will provide more info when I have it.

**Comment by NedtheNerd** [comment]
Obviously the volume slider is unique to the Android app as on the iOS app there is no volume slider in the remote - only next track, play/pause, previous track and disconnect, so unfortunately I can't test this - no android devices!

Have you tried the same method to control music playback on Plex HT on Windows/OSX - does produce the same result?

I have a feeling that this is an issue with the Android app not Rasplex.

I await your comments.

Regards

**Comment by muppet3000** [comment]
I'll try and have a play with this tonight.
I have a Windows client in the lounge which I can test on. 
I hadn't thought that it might be an issue with the android app, will try and rule it out, should be a case of plugging a keyboard in right?
Once I have some other information I'll post it, in the meanwhile if anyone has any more suggestions to add to the pile I'll see what I can test.

**Comment by NedtheNerd** [comment]
I decided to test this using Plex Web.

Started playback of album on Pi, switched to Plex Web, selected Pi for remote control, lowered volume to a minimum, turned amp up to full, adjusted volume in Plex Web to acceptable level and waited for track change - et voila - volume was the same (glad, otherwise I would have been deafened!).

Looks like an issue with the Android app (there has been in the past, volume control in - out - in, etc, see https://forums.plex.tv/index.php/topic/115532-volume-control-of-remote-clients-from-mobile-devices/?p=700838 - there are other similar posts scattered around the forums.

This is not a Rasplex issue, suggest that you raise this in the Android app forum, closing issue.
