### ISSUE TITLE
Rasplex skips video by about 20s

### ISSUE THREAD

**Issue by cmeister2** [RasPlex/RasPlex#290]
Required information:
Serial: 00000000c0d7a369
Debug log: http://sprunge.us/McNH
Rasplex version: RP-0.4.0-rc4
Plex version: 2.1.12

Size of Pi: 512
SD card: SDHC class 4
Internet connection: Ethernet
Installed rasplex: GUI installer

Best description of problem:
When playing some video files, occasionally they hang, then skip a number of seconds of video.

I had a quick look at the debug logs and the error appears to happen here:

11:20:18 T:2907698272   ERROR: COMXCoreComponent::DecoderEventHandler OMX.broadcom.audio_render - OMX_ErrorPortUnpopulated port 0, cannot parse input stream
11:20:18 T:2611999840    INFO: COMXAudioCodecOMX::GetChannelMap - FFmpeg reported 6 channels, but the layout contains 0 ignoring

though I could be wrong.

Steps to reproduce:
Rewind video to before the skip, and then press play.

Video of problem: https://www.dropbox.com/s/mi90e7yqaeyd5od/2014-07-26%2010.35.31.mp4

**Comment by dalehamel** [comment]
Is this still an issue in 0.5.1, or on RPi2?

**Comment by cmeister2** [comment]
Unsure I am afraid; I no longer use RasPlex, nor do I have an RPi2.

**Comment by NedtheNerd** [comment]
@g1t-dlanor is this still an issue, the OP appears to have left the Rasplex community, suggest closing as no one other than yourself or the OP has reported this.

**Comment by g1t-dlanor** [comment]
I still have the test video cmeister2 posted in a test media section of my PMS server, and have tested it with several of the recent RasPlex versions. The original problem remains unchanged in both RasPlex 0.5.0 and 0.5.1, but it is completely gone from the current 'buildset 8' beta I'm testing, both on the RPi1 (image ID 16) and on the RPi2 (image ID 15). I believe this to be fixed in all the recent test versions based on OpenELEC 5.
That said, the problem does remain unchanged in the last public releases.
So we need to be aware of that, in replying to possible user complaints in the forums.
Apart from that, I agree that it is time to close this issue, since it was fixed by our use of OE5, which should be included in the next public release.
