### ISSUE TITLE
Missing Zoom Slider

### ISSUE THREAD

**Issue by xomnia** [RasPlex/RasPlex#318]
I am running RasPlex 0.4.1 on a raspberry Pi B+ and am missing the "Zoom Amount" slider present on the "video OSD" in other builds.  I have checked latest x86 builds of plexHT on linux, windows, and osx and this slider is present in all of them.  It is missing on 4 different rPi B+ models I have set up with the current release of RasPlex.  I am unable to test with the standard rPi B model as I do not have any.

See https://forums.plex.tv/uploads/monthly_11_2014/post-60393-0-60025800-1416760525_thumb.png for an example of the "video OSD" screen to which I am referring.  You can see the Zoom Amount at the bottom of the dialog in that image, that is the option which appears to be missing in RasPlex.

**Comment by dalehamel** [comment]
Is this still an issue in 0.5.1 @xomnia?

**Comment by xomnia** [comment]
Just tested and yes, still missing.

**Comment by NedtheNerd** [comment]
Fixed in next release.

**Comment by theRoda** [comment]
There have been three releases since the last comment and still no zoom slider.

**Comment by NedtheNerd** [comment]
The 'zoom slider' is there, in the OSD when a video is playing go to the 'TV screen' icon at the far right, press enter and you wil see the 'zoom slider' - Zoom amount!

**Comment by theRoda** [comment]
I was referring to the slider when viewing a library, the one that in browser plex will increase poster and font size. I thought this was the slider OP was referring to.

**Comment by NedtheNerd** [comment]
@theRoda 

Look at the original date of the issue, how could he be referring to something that has only just been introduced in PlexWeb when the issue was raised in 2014?

**Comment by g1t-dlanor** [comment]
@theRoda 
Also, you need to keep in mind that the GUI presentation of one Plex client doesn't need to have the same features as the GUI presentation of an unrelated Plex client.

In OpenPHT/RasPlex such GUI rendering details as poster size are determined not by the main program, but by the loadable skin used. There are several such 3rd-party skins available having multiple view modes with varying poster size.

Finally, even the default 'Plex' skin of OpenPHT/RasPlex does have the ability to show larger posters.
This can be configured by setting the submenu option:
Preferences > Appearance > Advanced > Skin - Settings > "Show Big Posters View in Sections"
With that setting active each poster row will contain 5 posters, instead of the normal 8, and the number of such rows per screen is reduced from 3 to 2 (assuming normal screen resolutions).

**Comment by theRoda** [comment]
@g1t-dlanor
Thank you very much, that was particularly helpful information.
