### ISSUE TITLE
Perixx Peripad 701 bluetooth keyboard - linux kernel version issue

### ISSUE THREAD

**Issue by TechaY** [RasPlex/RasPlex#319]
Hello,

I've got the Perixx Peripad 701 bluetooth keyboard and unfortunately it can't work with openelec. The problem come from the linux kernel version used by OpenElec. My keyboard need linux kernel version 3.5.1 and above but OpenElec is using older version. The latest OpenElec release (5.0 beta 4) have updated to 3.17.4 so is still not possible (if you will updtate Rasplex with this release in the next couple week). 

I found a solution on the OpenElec forum. With a patch corresponding to the actual linux kernel version of openelec for rasplex, the driver can be update (as i understand...). see this link for more information : http://lii-enac.fr/en/architecture/linux-input/multitouch-howto.html#get

I would like to know if it's possible to implement this patch for the futur Rasplex Release ? 

Thank's.

**Comment by dalehamel** [comment]
Linux kernel updated in 0.5.1 to 3.18.6, is this still an issue @TechaY?

**Comment by NedtheNerd** [comment]
Will remain an issue until version 0.6.0, driver still not in current version

**Comment by NedtheNerd** [comment]
Bluetooth keyboards now fully supported in 0.7.1, closing issue.

**Comment by TechaY** [comment]
My keyboard Perixx Peripad 701 still doesn't work in 1.0.1.

Don't know why...

**Comment by g1t-dlanor** [comment]
@TechaY:
Bluetooth keyboard support was very problematic in older RasPlex versions, but for most people these problems have been cleared up with the latest releases. I myself am able to use a Bluetooth keyboard in recent versions without problems, though this always failed with various symptoms when using older RasPlex versions. But of course there are variations in the implementation of the Bluetooth protocol and pairing methods for different devices, which may be why it still doesn't work for you.

In order to clarify why it isn't working for you, and hopefully be able to fix that, we need more details on exactly what you have tried and the symptoms/results from those attempts. This may seem unnecessary to you, in case the symptoms simply were that the keyboard never was detected, but for us that knowledge in itself is important, since you haven't stated even that as yet.

Some info we want from you:
Have you tried that same keyboard, in its current state, for succesful use with a normal PC ?
Have you tried any other Bluetooth device, successfully pairing it with RasPlex ?

With your external Bluetooth dongle plugged into a USB port of the RPi, are you then able to enable the Bluetooth service of RasPlex in submenu: "System Settings" > "Services" > "Bluetooth" ?
That should be indicated in the adjacent submenu: "System Settings" > "Bluetooth"
which will contain the text "Bluetooth disabled" until you enable it, and which should thereafter show a list of all detected Bluetooth devices in the vicinity. It might also indicate absence of any bluetooth dongle by instead showing the text "No bluetooth adapter found.".

If your keyboard is shown in that list, and you select its entry and activate (presumably using keys or buttons of some other keyboard/remote), do you then  get any response at all when using the pairing procedure of the keyboard and entering the 6-digit code RasPlex prompts you to enter ?

Also, about that text entry: You need to press the 'Enter' key of your keyboard after entering the six digits, even though that last keypress is never mentioned in the popup. The keyboard is recognized already after just the digits, but the popup won't close until you press 'Enter'.

Note that for some keyboards there will be a delay before the keyboard activates, each time you turn the keyboard on again after having powered it off. For one of my keyboards that delay is appx 15-30 seconds... :( (Such complications are one reason I prefer non-bluetooth wireless keyboards.)

**Comment by TechaY** [comment]
Thank you @g1t-dlanor for your answer. I didn't receive mail (or missed it) about your response. 

I will take time tomorow to test everything you say. 

that i know already:

when i enable bluetooth in system settings, my bluetooth dongle is not detected and i see "No bluetooth adapter found."
This keyboard works fine with pc or tv. 
An other strange thing : when i connect the usb dongle and switch on my keyboard, if i touch an arrow key (up or down) i can see the marker on the screen moving but just from 1 position in menu section. It doesnt work after and i can't go up or down. This is happen everytime i try my keyboard in rasplex and since the begining (i'm using rasplex since two years or a bit more).

I will give you more information tomorow.

Thank's again :)

**Comment by g1t-dlanor** [comment]
The program responses you describe are quite strange, unlike anything I've seen with bluetooth keyboards in my testing. The fact that you get the message "No bluetooth adapter found" should mean that the system is completely unable to interact with any bluetooth keyboard through that dongle. And in any case, even with a bluetooth adapter detected and active, the system should never accept bluetooth keyboard entry without a properly registered pairing.

The failure to recognize a bluetooth dongle is indeed one reason why you never see the 6-digit code, as that only happens after you've put the keyboard into pairing mode and the OpenELEC system of RasPlex has detected this, showing an entry for the keyboard in the bluetooth device list, after which you should select that entry and choose to pair the unit in the popup menu that then should appear. But all of that is of course dependent on recognition of the bluetooth dongle, so without such recognition no interaction should be possible.

Are you 100% certain that this keyboard and its dongle are indeed using 'BlueTooth' for the interface, and not just non-bluetooth RF connection (which is what most of my own wireless keyboards use). Non-bluetooth wireless keyboards mostly connect to their dongles without any pairing procedure whatever (simple plug'n'play), while bluetooth keyboards normally require some pairing procedure (because they use shared RF frequencies and protocols). So if you didn't need a 'pairing' procedure with PC or TV, then the keyboard is probably not using bluetooth.

----- Some googling later -----

I've now found several pages describing this "Perixx Peripad 701", and it's always mentioned as a "2.4 GHz RF wireless keyboard", with no mention at all of the word "bluetooth", so in combination with the usage responses you've described I have to conclude that this is not a bluetooth unit. It uses a non-bluetooth RF transceiver USB dongle, and unfortunately this appears to be one of the few which are not compatible with the OpenELEC USB keyboard profiles. Apparently you just get one initial response and then the communication fails. Some very few USB keyboards have also failed to be compatible in the past, probably due to minor protocol variations. It's just bad luck that yours is in that group... :(

----- Some more googling later -----

I have now found an OpenELEC forum page where a user complains of exactly the same symptoms you described, in using exactly the same touchpad. He tried to use it with an OpenELEC install of XBMC(Frodo), where it failed to produce more than a single keypress response per session, just like you got with RasPlex.

My conclusion is that this is an OpenELEC issue still unsolved in current OpenELEC versions as used for RasPlex. It's not a bluetooth issue at all (as this pad is not a bluetooth device), but instead the problem lies in the pad's dual nature of being both a touchpad pointer interface and a keyboard device. That is apparently what causes the OpenELEC drivers to fail using it properly.

I don't think there's much we can do about this unless we get hold of an OpenELEC release that fixes this problem. Some of the pages I found discussed a patch for it, but I didn't find any clear statement as to whether or not this patch was adopted for the proper OE releases.
