### ISSUE TITLE
Keyboard key "S" for changing subtitles not working correctly

### ISSUE THREAD

**Issue by BIERAAP** [RasPlex/RasPlex#328]
When pressing the S key on the keyboard it used to change between subtitles available.
Currently its only changing between the selected subtitle and disabled.

**Comment by g1t-dlanor** [comment]
What you describe is not an error, but is part of the intended functionality.
This is how it is implemented in all versions of "Plex Home Theater", regardless of OS or hardware.

The "S" command is used to toggle the enabling of a selected subtitle On/Off.
The "L" command is used to step through the list of available subtitles, including one disabling step.
(I assume the "L" is short for "Language", though it works for multiple same-language subtitles too.)

Since there's no real issue here, but just a misunderstanding about the keyboard command usage, I'll now close this issue.
