### ISSUE TITLE
x265 HEVC codec support

### ISSUE THREAD

**Issue by jhg03a** [RasPlex/RasPlex#394]
Is there a plan to get directplay support for x265 (HEVC) codec support in rasplex for the raspberry pi 2?  I'm interested in the significant space savings it can give.

**Comment by NedtheNerd** [comment]
Eventually, no time frame at the moment.

**Comment by MattPark** [comment]
+1 This is apparently becoming a codec of choice

**Comment by KrunchMuffin** [comment]
+10

**Comment by BradMeier** [comment]
Neither the RPi1 or 2 has hardware decoding for HEVC, RPi2 may be able to scrape together 720p25 in software, but don't hold your breath, will work via transcoding in PMS though.

**Comment by KrunchMuffin** [comment]
bummer

**Comment by Ericmas001** [comment]
What about pi3?

**Comment by g1t-dlanor** [comment]
To my knowledge the GPU and all software for RPi3 (including firmware and kernels) is identical to that of the RPi2, except for some obvious hardware changes (such as internal WiFi). So even on the RPi3 HEVC will have to be handled by software decoding, which places a severe limit on the max bitrate it will support. That bitrate will be slightly higher, due to the higher clock rates, but HEVC in good quality  1080p and above will always require server-side transcoding. As for HEVC becoming  a 'codec of choice', this is obviously a choice made only by those who care more about video compression rates than they do about media player compatibility.

**Comment by JimmyS83** [comment]
HEVC HW support is the only thing, which is more and more pain of my Rpi2. Rpi3 doesnt have much to offer in home multimedia department, and I am afraid, that I will must buy some Amlogic S9xx for all TV's, as it doesnt seems to be priority for the RPF.  Need to say, it looks like majority of DVB-T switched or switching to the 1080 HEVC nowadays, and old signals are shutting down.
